Cloud function
codeu-spring2019/whats-that-doggo pull request #9
Opened 2019-04-10 22:32 UTC by michelaburns

Hey Rabab! I'm just making this a pull request so it's easier to find/see the code

2019-04-12 01:41 UTC, elithrar requested changes
A few comments. Outstanding questions:

- Did you test this by deploying it via the Cloud Functions section in the console?
- To test this without the front-end, use your terminal:

e.g. https://stackoverflow.com/questions/12667797/using-curl-to-upload-post-data-with-files

```sh
curl -XPOST $functionurlhere -F "imageBytes=@myimage.jpg"
```

Should return a result / status code.

2019-04-12 01:41 UTC, elithrar commented on function/index.js
> +  res.status(200).json(result).send(result.score);
You’ll want to send the entire result object here, so you don’t need to add the `.send()`

2019-04-12 01:41 UTC, elithrar commented on function/index.js
> +  if (scoreThreshold) {
You can elide this. Let the consumer (the web app) determine whether it’s useful to provide a cut-off.

2019-04-12 01:41 UTC, elithrar commented on function/index.js
>    // 3. Return the Auto ML label / score back in the response via res.send
Put these constants at the top of the file - above the function export line. 

Reason: they don’t need to be initialized on each request; just once.

2019-04-15 03:58 UTC, elithrar requested changes
Add this before the final existing `res.status` call:

```
res.set("Access-Control-Allow-Origin", "*")
```

Again, matching https://console.cloud.google.com/functions/details/us-central1/predict?project=sp19-codeu-35-7727&tab=source&duration=PT1H

2019-04-15 03:58 UTC, elithrar commented on function/index.js
> +@@ -19,14 +19,29 @@ exports.predictImage = (req, res) => {
Right after this line, add:

```
if (req.method === "OPTIONS") {
      res.set("Access-Control-Allow-Origin", "*")
      res.set("Access-Control-Allow-Headers", "Accept, Accept-Language, Content-Language, Content-Type")
      res.status(200).send()
    }
  
  	if (req.method !== "POST") {
      res.status(405).send()
    }
```

The browser needs this to send requests to a domain (the Cloud Functions one) different from where it’s hosted. 

Copied from the existing function: https://console.cloud.google.com/functions/details/us-central1/predict?project=sp19-codeu-35-7727&tab=source&duration=PT1H

2019-04-15 05:52 UTC, michelaburns commented
Hey Rabab! I added the changes Matt mentioned above. See: https://github.com/codeu-spring2019/whats-that-doggo/pull/10

2019-04-16 04:46 UTC, closed without merging